FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app
COPY ./ ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /app/out .

# Imposta ASP.NET Core a ascoltare su 5089
ENV ASPNETCORE_URLS=http://+:5089

# Espone la porta interna
EXPOSE 5089

ENTRYPOINT ["dotnet", "PrototipoApi.dll"]